settings:
    ue4_container_name: 'ue4'

gym:
    mode: 'train'
    env: 
        name: 'aereo_stereo_semisub_position_nbv'
        observation: 'stereo'
        reconstrucion: false
        vehicle_name : 'Hydrone'
        camera_name : 'stereo' 
        camera_dim:
            - 672
            - 376
        domain : 'aereo'
        observation_type : 'stereo'
        space_observation_dim : 1 
        space_action_dim : 5
        max_steps : 1000000

         
