
mode: 
    train :
        - 1
env: 
    semisub-position-aereo:
        vehicle : 
            name : 'Hydrone'
            start_pose:
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
            camera : 
                name : 'stereo' 
                dim:
                    - 672
                    - 376
        shadow:
            name : 'Shadow'
            start_pose:
                - 0
                - -8053.1
                - 0
                - 0
                - 0
                - 0
            camera : 
                name : 'shadow'
        domain : 'aereo'
        reconstrucion: false
        markers :
            name : Cube
            num : 175
        observation: 'stereo'
        max_steps : 1000000
        space_observation_dim : 3 
        space_action_dim : 5
        action_range:
            x:
                - -60
                - 60
            y :
                - -155
                - 155
            z :
                - -60
                - 60
            yaw : 
                - -45
                - 45
            gimbal_pitch:
                - -45
                - 45

    semisub-position-undewater:
        vehicle : 
            name : 'Hydrone'
            start_pose:
                - 0
                - 0
                - -8
                - 0
                - 0
                - 0
            camera : 
                name : 'stereo' 
                dim:
                    - 672
                    - 376
        shadow:
            name : 'Shadow'
            start_pose:
                - 0
                - -8053.1
                - -8
                - 0
                - 0
                - 0
            camera : 
                name : 'shadow'
        domain : 'underwater'
        reconstrucion: false
        markers :
            name : Sphere
            num : 63
        observation: 'stereo'
        max_steps : 1000000
        space_observation_dim : 3 
        space_action_dim : 5
        action_range:
            x:
                - -60
                - 60
            y :
                - -155
                - 155
            z :
                - -60
                - 60
            yaw : 
                - -45
                - 45
            gimbal_pitch:
                - -45
                - 45

         
