wandb_version: 1

learning_rate:
  desc: null
  value: 0.09
epochs:
  desc: null
  value: 10
init_steps:
  desc: null
  value: 4
max_steps:
  desc: null
  value: 1000000
eval_freq:
  desc: null
  value: 100000
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.17.0
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717369494
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
